---
- name: Ensure Jira system group present
  group:
    name: jira
    system: true

- name: Ensure Jira system user present
  user:
    name: jira
    group: jira
    comment: JIRA system user
    shell: /bin/false
    home: "{{jira_home_dir}}"
    createhome: no
    system: true

- name: Ensure Jira home directory present
  file:
    path: "{{jira_home_dir}}"
    state: directory
    owner: root
    group: jira
    mode: 0755

- name: Ensure Jira data directories present
  file:
    path: "{{item}}"
    state: directory
    owner: root
    group: jira
    mode: 0770
  with_items:
    - /var/lib/jira
    - /var/log/jira

- name: Download Jira distribution
  get_url:
    url: "https://www.atlassian.com/software/jira/downloads/binary/{{jira_package}}.tar.gz"
    dest: "/tmp/{{jira_package}}.tar.gz"
    owner: root
    group: root
    mode: 0644
  register: package_download

- name: Extract Jira distribution
  unarchive:
    src: "/tmp/{{jira_package}}.tar.gz"
    dest: "{{jira_home_dir}}"
    extra_opts: [ --strip-components=1 ]
    owner: root
    group: root
    mode: 0755
    remote_src: true
  when: package_download.changed

- name: Configure Jira system
  template:
    src: server.xml.j2
    dest: "{{jira_home_dir}}/conf/server.xml"
    owner: root
    group: root
    mode: 0644

- name: Symlink Jira logs directory
  file:
    path: "{{jira_home_dir}}/logs"
    state: link
    src: /var/log/jira
    force: true
    owner: root
    group: jira

- name: Grant write privileges to Jira system user
  file:
    path: "{{jira_home_dir}}/{{ item }}"
    owner: root
    group: jira
    mode: 0775
  with_items:
    - conf
    - temp
    - webapps
    - work

- name: Set home directory
  copy:
    dest: "{{jira_home_dir}}/atlassian-jira/WEB-INF/classes/jira-application.properties"
    content: "# Ansible managed - do not edit here!\njira.home=/var/lib/jira\n"

- name: Set Java options
  copy:
    dest: /etc/default/jira
    content: "# Ansible managed - do not edit here!\nJAVA_OPTS='{{ jira_java_opts }}'\n"

- include_tasks: postgresql.yml
  when: jira_configure_postgres

- name: Create Jira systemd script
  template:
    src: jira.service.j2
    dest: /etc/systemd/system/jira.service
    owner: root
    group: root
    mode: 0644
  register: jira_initd

- name: Ensure Jira service enabled and started
  systemd:
    name: jira.service
    state: started
    enabled: true
    daemon_reload: "{{jira_initd.changed}}"
