---
galaxy_info:
  author: idringvard
  description: Rsync for Nexus install
  license: "MIT"
  min_ansible_version: 2.7
  platforms:
    - name: EL
      versions:
        - 6
        - 7
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
        