galaxy_info:
  author: Igor Druzhynin
  description: Install JIRA software

  license: MIT

  min_ansible_version: 2.7

  galaxy_tags:
    - java
    - openjdk
    - jre
    - jira
    - jira-software
    - issue-tracker
    - atlassian

dependencies: []
