---
# tasks file for java
- name: Stat for OpenJDK archive
  stat:
    path: /tmp/{{openjdk_tarball}}"
  register: openjdk_archive

- name: Download OpenJDK archive
  get_url:
    url: "{{openjdk_url}}"
    dest: "/tmp/{{openjdk_tarball}}"
  register: downloaded
  when: not openjdk_archive.stat.exists

- name: Extract OpenJDK archive
  unarchive:
    src: "/tmp/{{openjdk_tarball}}"
    dest: "{{openjdk_directory}}"
    list_files: yes
    remote_src: yes
  register: java_files
  check_mode: no

- name: Set java directory variable
  set_fact:
    extracted_dir: "{{java_files.files[0].split('/')[0]}}"

- name: Setup environment variables
  template:
    src: jdk-env.sh.j2
    dest: /etc/profile.d/jdk-env.sh
    mode: 644

- name: Stat for java executable
  stat:
    path: /usr/bin/java
  register: java_link

- name: Remove symbolic link if present
  file:
    path: /usr/bin/java
    state: absent
  when: java_link.stat.exists

- name: Create symbolic links
  file:
    src: "{{openjdk_directory}}/{{extracted_dir}}/bin/java"
    path: /usr/bin/java
    state: link
    
